New user sequence
pbywater/echo pull request #113
Opened 2017-07-17 14:28 UTC by pbywater

Tutorial style intro when user has no memories

Relates to #108

2017-07-18 10:46 UTC, des-des requested changes
I am really not sure about this.

First, you need to fix the indentation.

There is too much repetition, you are repeating lots of functionality.

2017-07-18 10:46 UTC, des-des commented on src/client/d3/newUserIntro.js
> +                    .transition()
wtf indentation

2017-07-18 10:46 UTC, des-des commented on src/client/d3/newUserIntro.js
> +                      .transition()
This indentation is ridiculous

2017-07-18 10:46 UTC, des-des commented on src/client/d3/newUserIntro.js
> +      .selectAll('circle.node')
There is too much repetition here,

You are adding lots of complexity + branching with this feature.

I there no way you can use the old functionallity. Just pass in you mock data and run the tutorial, You are redefining to much stuff here.

Its not maintainable or good

2017-07-18 14:49 UTC, pbywater commented
@des-des I've fixed the horrible indentation (sorry!!!) and taken out as much code as I can. Weirdly we can't get the drag functions of similar to work if they move outside of the d3 file that they're being used in. The code is very repetitive with the timeouts and text changes but not sure how else to do this?

2017-07-19 11:18 UTC, des-des commented
As discussed yesterday, going to merge with master and try and run the dummy data though the old functionality

2017-07-20 11:36 UTC, des-des approved these changes

2017-07-20 11:36 UTC, merged