Fix mobile view
pbywater/echo pull request #120
Opened 2017-07-18 11:08 UTC by pbywater

- Removes ugly background colour on safari - relates to #119 
- Fixes background width on mobile - relates to #111

2017-07-18 13:37 UTC, des-des requested changes

2017-07-18 13:37 UTC, des-des commented on src/server/controllers/getMemories.js
> +  getMemories('test', (error, memories) => {
Are you sure?

2017-07-18 14:51 UTC, pbywater commented on src/server/controllers/getMemories.js
> +  getMemories('test', (error, memories) => {
@des-des Yup - without we have to keep logging in to access the memories so we're going to change it back later. @joeylouise

2017-07-19 11:16 UTC, des-des approved these changes

2017-07-19 11:16 UTC, merged