Implementing s3
pbywater/echo pull request #128
Opened 2017-07-19 15:57 UTC by joeylouise

This PR does 3 things

- When user adds memory, pushes to S3
- When view memory, pulls from S3
- When deleting, deletes from S3

#116 #125

2017-07-20 14:54 UTC, des-des requested changes
okay, need some work ...

But yeah congrats getting this working, I know its a real pain

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +      return alert('No file selected.');
? Is this good UX?

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +  xhr.onreadystatechange = () => {
Create a function in helpers called request. Use it here

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +        alert('Could not get signed URL.');
Not sure about these alerts ...

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +  const xhr = new XMLHttpRequest();
With a helper

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +  if (localStorage.getItem('addedImage')) {
Okay, this key represents if an upload is in progress.

Two things.
  1. I do not see why you need local storage for this.
  2. Is there a case where you are uploading more than 1 image / asset. Not really sure how you want to handle this
  3. You should call this imageUploadPending, and set it to true.

2017-07-20 14:54 UTC, des-des commented on public/scripts/s3-uploads.js
> +      success: localStorage.removeItem('addedImage'),
I expect you mean
```js
success: () => localStorage.removeItem('addedImage')
```

2017-07-20 14:54 UTC, des-des commented on src/database/db_get.js
> +const getMemoryUrlById = (id, callback) => {
Why cant you just use getMemoryById?

2017-07-20 14:54 UTC, des-des commented on src/database/db_update.js
> +     WHERE user_id = (SELECT users.id FROM users WHERE username = $1 OR email = $1)
```sql
WHERE user_id = (SELECT users.id FROM users WHERE username = $1 OR email = $1)
```
is the same as
```sql
WHERE username = $1 OR email = $1
```
?

I am fairly confused, this set the heading and tag of a memory, using it image id and user id?

2017-07-20 14:54 UTC, des-des commented on src/database/db_update.js
> +     WHERE user_id = (SELECT users.id FROM users WHERE username = $1 OR email = $1)
Hmm, why cant you just store the user Id in the session?

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/addPhotoMemory.js
> +  updatePhotoMemory('test', req.body.tag, req.body.heading, req.body.imageId, (err, res) => {
Your endpoints are authenticated??

This is problematic

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/getPhotoMemory.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
Bring this out into its own helper function

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/getPhotoMemory.js
> +    Key: req.query.memoryUrl,
Okay, there are 2 things you are missing here.

Firstly, you need to check if this memory belongs to the user!

I would

  1. Only keep the memoryId on the client (not the s3 key, helpfully called memoryUrl)
  2. In the endpoint, use the id from the session (this means that the user has been authenticated), and the memoryId, to find a the s3key for the memory.
  3. Make sure you check the memory belongs to the authenticated user!

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/getPhotoMemory.js
> +      return res.end();
this is unhelpful. what does the client do??
```js
res.status(500).send('failed to generate upload url')
```

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
Again, put the s3 init logic in a helper

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/getPhotoMemory.js
> +    Key: req.query.memoryUrl,
Okay,

  1. This is the s3 key, you should not give this to the client.
  2. The client should send the memoryId
  3. Use the memoryId to find the s3 key
  4. **Check that this memory belongs to the user**. Ie query the memories against the memoryId **and** the userId, to retrieve the s3Key

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/getPhotoMemory.js
> +      return res.end();
res.status(500).send('failed to generate asset URL')

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +const express = require('express');
Why is this called signS3, this is confusing.

I think you should call the files

`assetCreateUrl`, `assetGetUrl`, `assetDeleteUrl`.

Right now the naming is all over the place

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
Put this in a helper..

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +  createMemory('test', newMemory, 'image', fileKey, (err, res) => {
Hmm, this is not how you do async in js..
```js
(res, res) => {
  db.createMemory(res.body, err => {
    if (err) return res.status(500).send(message bla)
    s3.getSignedUrl(() => {
      res.success ..
    })
  })
}
```js

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +      return res.end();
Why no status code, no message ..

2017-07-20 14:54 UTC, des-des commented on src/server/controllers/signS3.js
> +    res.write(JSON.stringify(returnData));
```js
res.json(returnData)
```

2017-07-21 14:47 UTC, joeylouise commented on public/scripts/s3-uploads.js
> +      success: localStorage.removeItem('addedImage'),
I've changed this to

`success: () => { imageUploadPending = false; }`

2017-07-21 14:50 UTC, joeylouise commented on src/database/db_get.js
> +const getMemoryUrlById = (id, callback) => {
Have renamed this to getMemoryById

2017-07-21 14:52 UTC, joeylouise commented on src/server/controllers/getPhotoMemory.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
I've created an `s3init` function

2017-07-21 14:53 UTC, joeylouise commented on src/server/controllers/signS3.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
I've created an `s3init` function

2017-07-21 14:53 UTC, joeylouise commented on src/server/controllers/signS3.js
> +  aws.config.update({ accessKeyId: process.env.AWSAccessKeyId, secretAccessKey: process.env.AWSSecretKey, signatureVersion: 'v4', region: 'eu-west-2' });
I've created an `s3init` function

2017-07-21 14:54 UTC, joeylouise commented on src/server/controllers/signS3.js
> +  createMemory('test', newMemory, 'image', fileKey, (err, res) => {
I've refactored this 👍

2017-07-21 15:04 UTC, joeylouise commented on src/server/controllers/signS3.js
> +    res.write(JSON.stringify(returnData));
I've changed this

2017-07-21 15:06 UTC, joeylouise commented on src/server/controllers/getPhotoMemory.js
> +      return res.end();
I've added this in

2017-07-21 15:07 UTC, joeylouise commented on src/server/controllers/getPhotoMemory.js
> +      return res.end();
Added `res.status(500).send('failed to generate asset URL')`

2017-07-21 15:24 UTC, joeylouise commented on src/database/db_update.js
> +     WHERE user_id = (SELECT users.id FROM users WHERE username = $1 OR email = $1)
Cool, now storing user id in session as well
#152

2017-07-21 15:28 UTC, joeylouise commented on src/database/db_update.js
> +     WHERE user_id = (SELECT users.id FROM users WHERE username = $1 OR email = $1)
Passing in user.id now so have changed query to 

`WHERE user_id = $1`

2017-07-21 15:33 UTC, joeylouise commented on public/scripts/s3-uploads.js
> +  if (localStorage.getItem('addedImage')) {
I've removed where we use localStorage and instead are using imageUploadPending variable

2017-07-21 15:37 UTC, joeylouise commented on src/server/controllers/signS3.js
> +      return res.end();
Added status code and message

2017-07-21 15:39 UTC, joeylouise commented on src/server/controllers/addPhotoMemory.js
> +  updatePhotoMemory('test', req.body.tag, req.body.heading, req.body.imageId, (err, res) => {
Have changed test to `req.session.id`
Need to add authentication to all routes

2017-07-21 16:08 UTC, des-des commented
@joeylouise push?

2017-07-21 16:17 UTC, joeylouise commented
@des-des ok...have pushed some stuff, still working on it

2017-07-21 16:18 UTC, des-des commented
ah cool

2017-07-21 16:49 UTC, joeylouise commented on src/server/controllers/getPhotoMemory.js
> +    Key: req.query.memoryUrl,
k have refactored this now so that memory_asset_url is not kept on client

2017-07-21 16:50 UTC, joeylouise commented on src/server/controllers/getPhotoMemory.js
> +    Key: req.query.memoryUrl,
have done this now

2017-07-25 10:54 UTC, joeylouise commented
Hey @des-des I've made a bunch of changes to this, there are a couple of things I'm not sure about (making the xhr function in a helper and what to change the `alert`s to. Shall I assign to you to review so far or should we have a chat first?

2017-07-25 12:06 UTC, des-des commented
@joeylouise since we are both in the space lets just chat. Come grab me whenever

2017-07-31 15:19 UTC, joeylouise commented
Hey @des-des, I tried to refactor the xhr requests and everything kept breaking and I didn't want to take any more time refactoring so I have refactored a little bit and got rid of all alerts...

2017-07-31 16:42 UTC, des-des requested changes

2017-07-31 16:42 UTC, des-des commented on src/database/db_get.js
> +    if (err) return err;
:scream: the callback is not being called when you have an error

2017-07-31 16:42 UTC, des-des commented on src/server/app.js
> +const aws = require('aws-sdk');
does this do anything?

2017-07-31 16:42 UTC, des-des commented on src/server/app.js
> +const S3_BUCKET_NAME = process.env.S3_BUCKET;
and this?

2017-07-31 16:42 UTC, des-des commented on src/server/controllers/assetCreateUrl.js
> +      res.end();
Do you need to call res.json and res.end?

2017-07-31 16:42 UTC, des-des commented on src/server/controllers/assetDeleteUrl.js
> +  deleteMemory(req.body.id, (error, response) => {
You should nest all you async stuff, right now you are running s3.delete object and deleteMemory in parallel.

Put one inside the other, or use async.parallel.

2017-07-31 16:42 UTC, des-des commented on src/server/controllers/assetDeleteUrl.js
> +      else console.log(data);
not sure you want to log this

2017-08-01 14:39 UTC, joeylouise commented
@des-des cool. 👍

2017-08-02 13:29 UTC, des-des approved these changes

2017-08-02 13:29 UTC, merged