Service worker
pbywater/echo pull request #145
Opened 2017-07-20 16:42 UTC by pbywater

- Adds service worker
- Caches most of the files (still an issue with the font)
- Saves data to render nodes offline
- User can remove a memory whilst offline
- Memory will delete from database when user goes back online

2017-07-20 16:46 UTC, ghost approved these changes

2017-07-21 11:17 UTC, des-des requested changes

2017-07-21 11:17 UTC, des-des commented on src/client/d3/d3.js
> +if ('serviceWorker' in navigator) {
Put this in your main js file!

2017-07-21 11:17 UTC, des-des commented on public/service-worker.js
> +/* eslint-disable */
Can you link the me where you got this file

2017-07-21 11:17 UTC, des-des commented on public/service-worker.js
> +/* eslint-disable */
I mean, drop a link in as a comment

2017-07-21 11:17 UTC, des-des commented on src/client/d3/d3.js
> +        render(formatData(data));
this is called by update, do you want to run it twice?

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +    localStorage.toDelete = saveMemoriesToDelete;
localStorage.setItem('toDelete' ?

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +    const saveDeletedMemory = JSON.stringify({memories: [id]});
Hmm, not sure this works, should be an array `[{memories: [id]}]`

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +    localStorage.toDelete = saveDeletedMemory;
setItem

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +  localStorage.data = offlineDataAfterRemoving;
setItem

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +  memoriesWaitingToBeRemoved.memories.splice(index, 1);
indentation

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +function saveMemoryIdToStorage(id) {
This name is confusing.

`setMemoryDeletePending`?

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +    localStorage.toDelete = saveMemoriesToDelete;
We can refac this
```js
const toDeleteJSON = localStorage.getItem('toDelete')
const toDelete = (toDeleteJSON ? JSON.parse(toDeleteJSON) : []).concat(id)
localStorage.setItem(
  'toDelete',
  JSON.stringify(toDelete)
)
```

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +function removeMemoryFromLocalStorage(index) {
`cancelMemoryPendingDelete`?

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +function removeMemoriesDeletedOffline(cb) {
`deletePendingMemories`

2017-07-21 11:17 UTC, des-des commented on src/client/helpers/helpers.js
> +  deletedMemories.memories.forEach((memory, index) => {
This is bad..

You should use `async.parrallel`
https://caolan.github.io/async/docs.html#parallel

If you do not feel confident doing this dw

2017-07-21 13:32 UTC, pbywater commented on src/client/helpers/helpers.js
> +  deletedMemories.memories.forEach((memory, index) => {
I'm not really too sure how to implement this here!

2017-07-21 16:06 UTC, des-des approved these changes

2017-07-21 16:06 UTC, merged