S3 offline logic
pbywater/echo pull request #171
Opened 2017-08-03 16:29 UTC by pbywater

Relates to #163 #170 
- Saves base64 encoded url to localStorage whilst offline
- Decodes and uploads to database and s3 once back online
- Limits users to one offline media upload and alerts them if they are trying to do more
- Refactors code so it works with audio too

2017-08-04 08:54 UTC, ghost approved these changes

2017-08-05 11:11 UTC, des-des requested changes
@pbywater 

Hi I know are kinda tight on time etc etc, but I would **strongly** recommend you refactor this to stop using global vars. Its evil, fragile and unmaintainable.

Further, the es6 code you have written will crash older browsers if you are not passing it through your build process.

Sorry I did not pick this up earlier..

2017-08-05 11:11 UTC, des-des commented on public/scripts/s3-helpers.js
> +    const retrievedFile = dataURLtoFile(image, fileName);
image is undefined?

2017-08-05 11:11 UTC, des-des commented on public/scripts/s3-helpers.js
> +    success: () => { uploadPending = false; },
No global scope please. Where has this come from?

Not sure what is going on / how I missed this, but you want to be writing your code with require / module.exports.

Everything in the top level of this file is declared in global scope. Further, this code is not being passed though babel (you browserify script does this).

That means your arrow functions are not being converted into es5 and will break some browsers

2017-08-05 11:11 UTC, des-des commented on public/scripts/s3-helpers.js
> +function dataURLtoFile(dataurl, filename) {
please link to the source of code that you have copy pasted

2017-08-05 11:11 UTC, des-des commented on public/scripts/s3-uploads.js
> +  (function () {
This iife is nonsense.

You need to use require / module.exports. This is no no good we are going backwards!

2017-08-05 11:11 UTC, des-des commented on public/scripts/s3-uploads.js
> +          uploadPending = true;
:scream:

2017-08-05 18:40 UTC, pbywater commented on public/scripts/s3-uploads.js
> +          uploadPending = true;
Haha - this was all the code that was merged before!! I will take a look and refactor

2017-08-08 17:25 UTC, des-des requested changes

2017-08-08 17:25 UTC, des-des commented on public/scripts/s3-helpers.js
> +function saveFileToLocalStorage(file, fileSource) {
cool, this file should live in src

2017-08-08 17:25 UTC, des-des commented on src/client/main.js
> +require('./../../public/scripts/sign-up.js');
yeah, all these files should now move to src!

2017-08-08 17:25 UTC, des-des commented on public/service-worker.js
> +  '/scripts/main.js',
There should only be 1 bundle? No other scripts?

2017-08-08 17:25 UTC, des-des commented on public/scripts/s3-uploads.js
> +function s3handling(fileSource) {
can we export this, then call it in main. (if that makes sense, right now this function gets executed when it is required, but that can be very hard to follow)

2017-08-11 14:08 UTC, merged