Add initial file structure
pbywater/echo pull request #22
Opened 2017-06-26 16:28 UTC by joeylouise

This PR sets up the initial file structure, including following folders and files:

- public
- src
- database_build
- tests
- eslint
- package.json

Relates #1

2017-06-26 20:25 UTC, des-des requested changes

2017-06-26 20:25 UTC, des-des commented on public/scripts/d3/margins.js
> +var width = 1000;
Width here has global scope

You need to decide how you are going to modularize your code.

Using an iife is the easiest option, happy to go into more detail if you like

2017-06-26 20:25 UTC, des-des commented on public/main.css
> +svg {
You want to apply this to all svgs?

2017-06-26 20:25 UTC, des-des commented on public/index.html
> +
Hmm, are you planning on using a canvas element?

A canvas is a html5 thing that I expect you will not use. The name is misleading

2017-06-26 20:25 UTC, des-des commented on public/scripts/d3/margins.js
> +    // .attr("background-color", "pink")
No comments please

2017-06-26 20:25 UTC, des-des commented on public/scripts/d3/margins.js
> +    // .attr("background-color", "pink")
I mean commented out code. If you want to merge some commented code into master, then leave a comment to explain why it needs to stay

2017-06-26 20:26 UTC, des-des commented
Final thing, try to add issue numbers to *all* commits, not sure I might have forgot to mention that

2017-06-27 09:18 UTC, ConchobarMacNessa commented on public/scripts/d3/margins.js
> +var width = 1000;
Hi, we wanted to give width/heigh etc global scope as it's likely we'll need to refer to it later on in our d3 code – if we use an iife I don't think we'll have access to the variable, right?

2017-06-27 11:41 UTC, des-des approved these changes

2017-06-27 13:53 UTC, merged