Refactored code
pbywater/echo pull request #47
Opened 2017-07-04 13:30 UTC by pbywater

- Added watchify
- Added tests (some need to be fixed now)
- Made functions testable/ purer
- Nodes and links now appear on page but draggable function isn't fully working yet
- Added comments/removed commented out code

2017-07-04 14:46 UTC, ghost approved these changes

2017-07-04 16:42 UTC, des-des approved these changes

2017-07-04 16:42 UTC, des-des commented on src/client/helpers/helpers.js
> +function calculateXY(nodeList) {
Would be better to map the nodes then foreach + mutate

2017-07-04 16:42 UTC, des-des commented on src/client/helpers/helpers.js
> +function onlyUnique(value, index, self) {
I think you are not using this function (:fire:)

2017-07-04 16:42 UTC, des-des commented on src/client/node_transformations.js
> +    out[tag.max.tag] = {
tag === tag.max.tag?

2017-07-04 16:42 UTC, des-des commented on src/client/node_transformations.js
> +const getMemoryNodePositions = (tagNode, numTagMemories, memoryIndex, currentAvgRating) => {
:+1:

2017-07-04 16:42 UTC, des-des commented on src/client/node_transformations.js
> +    const memoryNodes = tagMemoriesRest.map((tagMemory, memoryIndex) => {
Remove `const memoryNodes = ` variable called `memoryNodes` not being used
`tagMemoriesRest.map((tagMemory, memoryIndex) => {`

2017-07-04 16:42 UTC, des-des commented on tests/src/client/node_transformations.js
> +  const expected = { family: { avgRating: 9.2, id: 0, likes: 19, tag: 'family', x: 160, y: 120 }, friends: { avgRating: 9.2, id: 1, likes: 19, tag: 'friends', x: 160, y: 320 }, pets: { avgRating: 9.2
Break this over multiple lines!

2017-07-04 16:42 UTC, des-des commented on tests/src/client/node_transformations.js
> +  const memoriesByTag = { family: { avgRating: 9.2, id: 0, likes: 19, tag: 'family', x: 160, y: 120 }, friends: { avgRating: 9.2, id: 1, likes: 19, tag: 'friends', x: 160, y: 320 }, pets: { avgRating
And this

2017-07-04 16:43 UTC, des-des requested changes
ops wrong button

2017-07-04 16:44 UTC, des-des commented
:tada:

2017-07-04 17:01 UTC, pbywater commented on src/client/node_transformations.js
> +    out[tag.max.tag] = {
That's confusing.. But I think right! Not sure if there's a better way of phrasing it

2017-07-04 17:02 UTC, pbywater commented
@des-des All done I think!

2017-07-05 12:05 UTC, des-des commented
delete calculateXY and will merge

2017-07-05 12:09 UTC, pbywater commented
@des-des deleted! :)

2017-07-05 13:32 UTC, des-des approved these changes

2017-07-05 13:32 UTC, merged