Menu and tagging
pbywater/echo pull request #55
Opened 2017-07-06 11:08 UTC by pbywater

- Added shuffle and search buttons
- Animation on tag/search menu
- Added unique tags based on data
- Added ability to filter by tag by clicking on an individual tag or by removing tags
- Added ability to clear filter

2017-07-06 11:10 UTC, joeylouise commented
This PR also
-adds the sticky menu to the homepage
-adds all icons into assets folder

Relates #15 #7

2017-07-06 11:20 UTC, ConchobarMacNessa commented
Also links up the main three 'source' nodes to one another
relates #52

2017-07-06 11:41 UTC, des-des requested changes
Remove all the DS_Store files, change your git ignore so these do not come up again..
`public/assets/icons/menu/notification/_DS_Store`

2017-07-06 11:49 UTC, des-des requested changes

2017-07-06 11:49 UTC, des-des commented on .gitignore
> +.DS_Store
**/*DS_Store

might do it ..?

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +  z-index: 999999;
`z-index: 2` is prob okay

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +     display: none;
indentaion

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +      list-style-type: none;
indentation

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +  z-index: 99999;
too big

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +    display: inline-block;
indentation

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +.underline:after {
is underline the best class name?

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +width: 10%;
indentaion

2017-07-06 11:49 UTC, des-des commented on public/main.css
> +    background: transparent !important;
indentation

2017-07-06 11:49 UTC, des-des commented on public/scripts/main.js
> +document.addEventListener('DOMContentLoaded', (event) => {
This file needs to be refactored, heavily. Talk to me if you do not know how

2017-07-06 11:49 UTC, des-des commented on src/client/d3/d3.js
> +      `<li class='tag-container ${tag}'>
Vulnerable to script injection attacks

2017-07-06 11:49 UTC, des-des commented on src/client/helpers/helpers.js
> +      $('.shuffle-memories').fadeIn(1000);
You have variables like, 1000, and 500 scattered around everywhere.

Make a variable?

2017-07-06 11:54 UTC, pbywater commented on public/main.css
> +.underline:after {
It refers to a line that extends underneath the tags - would there be a better name for it?

2017-07-06 11:55 UTC, pbywater commented on public/main.css
> +  z-index: 999999;
Haha I'll change these

2017-07-06 16:04 UTC, joeylouise commented on public/scripts/main.js
> +document.addEventListener('DOMContentLoaded', (event) => {
Nice and refactored now! 👍

2017-07-07 09:57 UTC, des-des approved these changes

2017-07-07 09:57 UTC, merged