Submit text memory to db
pbywater/echo pull request #66
Opened 2017-07-10 09:33 UTC by joeylouise

**Merge #61 first please**

This PR:

Reorders db_build.sql so that build builds correctly
Adds routes to create memory in db for text memory

Relates #57 #59

2017-07-10 11:19 UTC, des-des commented
Merge and re-assign -- this has commits from other pulls on it!!

2017-07-10 12:52 UTC, joeylouise commented
@des-des fixed now!

2017-07-10 16:39 UTC, des-des requested changes
Coolio,

You do not need to do it in this pull, but check out
https://github.com/pbywater/echo/issues/70

2017-07-10 16:39 UTC, des-des commented on src/routes/addTextMemory.js
> +app.use(bodyParser());
No, this should be in the root file

2017-07-10 16:39 UTC, des-des commented on src/routes/addTextMemory.js
> +        result.redirect('/');
assuming this is temporary?

2017-07-11 10:32 UTC, pbywater commented on src/routes/addTextMemory.js
> +app.use(bodyParser());
@joeylouise - router bits have been fixed in deleting-node branch

2017-07-11 10:47 UTC, des-des approved these changes

2017-07-11 10:47 UTC, merged