Deleting Node
pbywater/echo pull request #68
Opened 2017-07-10 14:21 UTC by pbywater

relates to #20 #21 

- After a few seconds of dragging a node, the menu disappears and a bin button appears
- Bin changes colour on hover
- Node deletes from the database when user drops it in the bin

2017-07-10 16:43 UTC, des-des requested changes

2017-07-10 16:43 UTC, des-des commented on src/routes/deleteMemory.js
> +  app.delete('/memories', (req, result) => {
this is the same as

```js
app.delete('/memories', (req, result) => { /*...*/ }

module.exports = [
  app
]
```
se #70

2017-07-11 10:31 UTC, pbywater commented
@des-des - I changed the error handling to `console.error(err)` - does that make sense?!

2017-07-11 10:40 UTC, des-des requested changes

2017-07-11 10:40 UTC, des-des commented on src/server/controllers/getMemories.js
> +module.exports = (req, result) => {
ok, in express we say `(req, res)` or `(request, response)`

2017-07-11 10:40 UTC, des-des commented on src/server/controllers/getMemories.js
> +  getMemories(1, (err, res) => {
```js
module.exports = (req, res) => {
  getMemories(1, (err, memories) => {
    if(err) return res(err); // return is to exit the function, not actually return
   // same as if(err) {res(err); return; }
   result.send(memories.rows);
  }
}

2017-07-11 10:40 UTC, des-des commented on src/server/controllers/home.js
> +  res.sendFile(path.join(`${__dirname}/..` + '/public/index.html'));
Do not use template literal, thats what path.join does
```js
path.join(__dirname, '..', 'public', 'index.html')
```

2017-07-12 12:32 UTC, des-des approved these changes

2017-07-12 12:32 UTC, merged