Call createUser function and add functionality to sign up / login forms
pbywater/echo pull request #91
Opened 2017-07-13 15:54 UTC by joeylouise

This PR:

Calls createUser function at add-new-user route
Displays signup.html at sign-up route
Adds logic to switch between login and sign up forms
Fix some indentation in main.css sign up form styling

Relates #79

2017-07-14 10:10 UTC, des-des requested changes

2017-07-14 10:10 UTC, des-des commented on src/server/controllers/addNewUser.js
> +      res.send({ error: error.message });
The status should not be 200.
res.status(400).send({error: })

2017-07-14 10:28 UTC, joeylouise commented on src/server/controllers/addNewUser.js
> +      res.send({ error: error.message });
Thanks 👍 that's done now

2017-07-17 09:00 UTC, des-des approved these changes

2017-07-17 09:00 UTC, merged