Create / clear user cookie
pbywater/echo pull request #97
Opened 2017-07-14 14:22 UTC by joeylouise

This PR:

Requires cookie-parser module
Adds dummy logout button with styling
Create cookie when user is authenticated
Clear cookie when user logs out
Relates #94

2017-07-17 09:31 UTC, des-des requested changes
Okay, right now this is not secure, you have no way of verifying that a cookie returned sent by a client is authentic. I would use the cookie-session npm module. This will sign and verify your cookie.

2017-07-17 09:31 UTC, des-des commented on src/server/controllers/login.js
> +        res.cookie('name', login, { maxAge: 3600000 }).redirect('/');
Is this one hour?

I would write it as 1000 * 60 * 60, otherwise it is hard to know what it means

2017-07-17 16:28 UTC, joeylouise commented
@des-des I've changed this to use cookie-session and have set req.session.name when user logs in.

I've added in the session in `router.js` because it doesn't work when I add it in `app.js`

2017-07-18 10:20 UTC, des-des approved these changes
coolio looks good

2017-07-18 10:20 UTC, des-des commented on src/server/router.js
> +const sessionSecret = '3294r4whasuodifhd13urde80sufj138ryt9-gu538re9ghvisujela4hrsf4rue5r89';
No! Do not commit this. Put it in the env file!

2017-07-18 10:20 UTC, des-des commented on package.json
> +    "cookie-parser": "^1.4.3",
Do you need this?

2017-07-18 10:21 UTC, des-des requested changes
Ops see review above

2017-07-18 10:57 UTC, des-des approved these changes

2017-07-18 10:59 UTC, merged